<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Nominal_model extends CI_Model
{

    public $table = 'nominal';
    public $id = 'id';
    public $order = 'ASC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL)
    {
        $this->db->like('id', $q);
        $this->db->or_like('id_kategori', $q);
        $this->db->or_like('infaq_gedung', $q);
        $this->db->or_like('infaq_perpustakaan', $q);
        $this->db->or_like('infaq_kegiatan', $q);
        $this->db->or_like('buku_dan_media_pembelajaran', $q);
        $this->db->or_like('seragam_dan_attribut_sekolah', $q);
        $this->db->or_like('jilbab', $q);
        $this->db->or_like('pendidikan_infaq_pengembangan', $q);
        $this->db->or_like('total', $q);
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL)
    {
        $this->db->from('nominal');
        $this->db->join('kategori', 'nominal.id_kategori=kategori.id_kategori');
        $this->db->order_by('nominal.id_kategori', $this->order);
        $this->db->like('nominal.id', $q);
        $this->db->or_like('nominal.id_kategori', $q);
        $this->db->or_like('nominal.infaq_gedung', $q);
        $this->db->or_like('nominal.infaq_perpustakaan', $q);
        $this->db->or_like('nominal.infaq_kegiatan', $q);
        $this->db->or_like('nominal.buku_dan_media_pembelajaran', $q);
        $this->db->or_like('nominal.seragam_dan_attribut_sekolah', $q);
        $this->db->or_like('nominal.jilbab', $q);
        $this->db->or_like('nominal.pendidikan_infaq_pengembangan', $q);
        $this->db->or_like('total', $q);
        $this->db->limit($limit, $start);
        return $this->db->get()->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }
}

/* End of file Nominal_model.php */
/* Location: ./application/models/Nominal_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-03-06 21:30:38 */
/* http://harviacode.com */
